Repository SSAFY-TOTT/Android, pull requests merged in 2023-09, with the labels that each got.

#3 Feature/#1
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/ui/searchfilter/SearchFilterActivity.kt
  app/src/main/res/drawable/ic_done.xml
  app/src/main/res/layout/activity_search_filter.xml
  app/src/main/res/menu/menu_toolbar_search_filter.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/values.xml
Labels: feat

#4 기본 디자인 변경
  app/src/main/res/layout/activity_search_filter.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feature

#7 집 찾기 화면 바텀 시트 추가
  app/build.gradle.kts
  app/src/main/java/com/ssafy/tott/domain/model/SimpleHouse.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/SimpleHouseListAdapter.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/SimpleHouseViewHolder.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SimpleHouseListDialogFragment.kt
  app/src/main/res/layout/activity_search_map.xml
  app/src/main/res/layout/item_simple_house.xml
  app/src/main/res/layout/rv_simple_house.xml
Labels: ✨ feature

#8 지도에 사용할 마커 클래스 데이터 변경
  app/src/main/java/com/ssafy/tott/domain/model/Building.kt
  app/src/main/java/com/ssafy/tott/domain/model/BuildingDetail.kt
  app/src/main/java/com/ssafy/tott/domain/model/House.kt
  app/src/main/java/com/ssafy/tott/ui/model/ClusterMarker.kt
Labels: ✨ feature

#11 매물 목록 화면 구현
  app/src/main/java/com/ssafy/tott/domain/model/Building.kt
  app/src/main/java/com/ssafy/tott/domain/model/BuildingDetail.kt
  app/src/main/java/com/ssafy/tott/domain/model/SimpleHouse.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/BuildingDetailListAdapter.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/BuildingDetailViewHolder.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/SimpleHouseViewHolder.kt
  app/src/main/java/com/ssafy/tott/ui/map/SimpleHouseListDialogFragment.kt
  app/src/main/java/com/ssafy/tott/ui/model/BuildingDetailUI.kt
  app/src/main/res/layout/item_building_detail.xml
  app/src/main/res/layout/item_simple_house.xml
  app/src/main/res/layout/rv_building_detail.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: ✨ feature

#12 매물 상세 화면 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/ui/buildingdetail/BuildingDetailActivity.kt
  app/src/main/java/com/ssafy/tott/ui/model/BuildingDetailUI.kt
  app/src/main/res/drawable/ic_favorite.xml
  app/src/main/res/layout/activity_building_detail.xml
  app/src/main/res/menu/menu_building_detail.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#18 로그인 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/ui/MainActivity.kt
  app/src/main/java/com/ssafy/tott/ui/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feature

#19 회원가입 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/ui/login/LoginActivity.kt
  app/src/main/java/com/ssafy/tott/ui/register/RegisterActivity.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: ✨ feature

#20 필터 설정한 데이터 서버에 전달
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/data/datasource/BuildingDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/repository/BuildingRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/domain/repository/SearchBuildingRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/SearchBuildingUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/model/ClusterMarker.kt
  build.gradle.kts
Labels: ✨ feature

#22 회원 가입 인증 번호 요청
  app/build.gradle.kts
  app/src/main/java/com/ssafy/tott/data/datasource/AccountDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/mapper/UserMapper.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/AccountDataSourceRemote.kt
  app/src/main/java/com/ssafy/tott/data/model/RegisterAccountRequest.kt
  app/src/main/java/com/ssafy/tott/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/domain/exception/Exceptions.kt
  app/src/main/java/com/ssafy/tott/domain/model/RegisterUser.kt
  app/src/main/java/com/ssafy/tott/domain/repository/UserRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/RegisterUserUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/register/RegisterActivity.kt
  app/src/main/java/com/ssafy/tott/ui/register/RegisterViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#25 매물 검색을 실제 서버에서 가져오도록 변경
  app/src/main/java/com/ssafy/tott/data/datasource/BuildingDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/model/request/SearchFilterRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingDetailResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingListResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingResponse.kt
  app/src/main/java/com/ssafy/tott/data/repository/BuildingRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/ApiService.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/di/NetworkModule.kt
  app/src/main/java/com/ssafy/tott/domain/model/Building.kt
  app/src/main/java/com/ssafy/tott/domain/model/BuildingDetail.kt
  app/src/main/java/com/ssafy/tott/domain/repository/SearchBuildingRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/SearchBuildingUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapViewModel.kt
Labels: ✨ feature

#26 집 찾기 필터링 값 변경 & 스타일 수정
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/searchfilter/SearchFilterFragment.kt
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
  app/src/main/res/values/values.xml
Labels: ✨ feature

#28 매물 목록 화면과 매물 상세 정보 화면 연결
  app/src/main/java/com/ssafy/tott/ui/buildingdetail/BuildingDetailActivity.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/BuildingDetailListAdapter.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/BuildingDetailViewHolder.kt
  app/src/main/java/com/ssafy/tott/ui/map/SimpleHouseListDialogFragment.kt
  app/src/main/java/com/ssafy/tott/ui/util/ImageLoader.kt
  app/src/main/java/com/ssafy/tott/ui/util/SerializeGetter.kt
Labels: ✨ feature

#30 집 찾기 지도 마커 클릭 기능 추가
  app/src/main/java/com/ssafy/tott/di/ApiService.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SimpleHouseListDialogFragment.kt
  app/src/main/java/com/ssafy/tott/ui/model/BuildingDetailUI.kt
  app/src/main/java/com/ssafy/tott/ui/util/SerializeMapper.kt
Labels: ✨ feature

#32 메인 화면 레이아웃 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/ui/MainActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeViewModel.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_home.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#35 매물 찾기 화면에서 받는 API 스펙 변경
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingDetailResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingListResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingResponse.kt
  app/src/main/java/com/ssafy/tott/domain/model/Building.kt
  app/src/main/java/com/ssafy/tott/domain/model/BuildingDetail.kt
  app/src/main/java/com/ssafy/tott/domain/model/HouseSaleArticle.kt
  app/src/main/java/com/ssafy/tott/ui/buildingdetail/BuildingDetailActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/BuildingDetailListAdapter.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SimpleHouseListDialogFragment.kt
  app/src/main/java/com/ssafy/tott/ui/model/BuildingDetailUI.kt
  app/src/main/java/com/ssafy/tott/ui/model/ClusterMarker.kt
  app/src/main/java/com/ssafy/tott/ui/register/RegisterActivity.kt
Labels: ✨ feature

#37 로그인 기능 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/data/datasource/UserDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/local/DataStoreManager.kt
  app/src/main/java/com/ssafy/tott/data/datasource/local/UserTokenDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/local/UserTokenDataSourceImpl.kt
  app/src/main/java/com/ssafy/tott/data/datasource/mapper/ErrorMapper.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/AccountDataSourceRemote.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserDataSourceRemote.kt
  app/src/main/java/com/ssafy/tott/data/model/request/ErrorRemoteResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/request/LoginRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/response/AuthTokenRemoteResponse.kt
  app/src/main/java/com/ssafy/tott/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/ApiService.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/di/DataStoreModule.kt
  app/src/main/java/com/ssafy/tott/di/NetworkModule.kt
  app/src/main/java/com/ssafy/tott/domain/exception/Exceptions.kt
  app/src/main/java/com/ssafy/tott/domain/model/AuthToken.kt
  app/src/main/java/com/ssafy/tott/domain/repository/UserRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/LoginUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/login/LoginActivity.kt
  app/src/main/java/com/ssafy/tott/ui/login/LoginViewModel.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#39 회원가입 기능 구현
  app/src/main/java/com/ssafy/tott/data/datasource/UserDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/mapper/UserMapper.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserDataSourceRemote.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/UserService.kt
  app/src/main/java/com/ssafy/tott/data/mapper/ErrorMapper.kt
  app/src/main/java/com/ssafy/tott/data/model/RegisterAccountRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/request/SignupRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/request/VerificationRequest.kt
  app/src/main/java/com/ssafy/tott/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/ApiService.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/di/NetworkModule.kt
  app/src/main/java/com/ssafy/tott/domain/repository/UserRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/RegisterCertUseCase.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/RegisterUserUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/register/RegisterActivity.kt
  app/src/main/java/com/ssafy/tott/ui/register/RegisterViewModel.kt
  app/src/main/res/layout/activity_register.xml
Labels: ✨ feature

#43 토큰 관리 기능 구현
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/UserService.kt
  app/src/main/java/com/ssafy/tott/data/model/response/AuthTokenRemoteResponse.kt
  app/src/main/java/com/ssafy/tott/di/NetworkModule.kt
  app/src/main/java/com/ssafy/tott/domain/exception/Exceptions.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/GetAuthTokenUseCase.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/LoginUseCase.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/SaveAuthTokenUseCase.kt
Labels: 🚑 fix, ✨ feature

#46 HouseDetailView 수정
  app/src/main/res/drawable/ic_area.xml
  app/src/main/res/drawable/ic_floor.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/layout/activity_building_detail.xml
  app/src/main/res/layout/fragment_search_filter.xml
Labels: ✨ feature

#47 최근 본 집 목록 호출 기능 구현
  app/src/main/java/com/ssafy/tott/data/datasource/BuildingDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/BuildingService.kt
  app/src/main/java/com/ssafy/tott/data/model/request/BuildingDetailIdListRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingDetailsResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/HouseDetailResponse.kt
  app/src/main/java/com/ssafy/tott/data/repository/BuildingRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/ApiService.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/di/NetworkModule.kt
  app/src/main/java/com/ssafy/tott/domain/repository/BuildingRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/GetRecentHouseArticlesUseCase.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/SearchBuildingUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeViewModel.kt
  app/src/main/res/layout/item_building_detail.xml
Labels: 🚑 fix, ✨ feature

#52 매물 찾기 필터 API 수정
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/BuildingService.kt
  app/src/main/java/com/ssafy/tott/data/model/request/SearchFilterRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingDetailResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BuildingResponse.kt
  app/src/main/java/com/ssafy/tott/domain/model/Region.kt
  app/src/main/java/com/ssafy/tott/domain/model/SearchFilter.kt
  app/src/main/java/com/ssafy/tott/ui/buildingdetail/BuildingDetailActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapActivity.kt
  app/src/main/java/com/ssafy/tott/ui/map/SearchMapViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/searchfilter/SearchFilterFragment.kt
  app/src/main/res/layout/activity_building_detail.xml
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#53 홈 화면에서 위시 리스트 호출
  app/src/main/java/com/ssafy/tott/data/datasource/BuildingDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/BuildingService.kt
  app/src/main/java/com/ssafy/tott/data/repository/BuildingRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/domain/repository/BuildingRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/GetWishListUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeViewModel.kt
Labels: ✨ feature

#55 추가자산 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserDataSourceRemote.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserRemoteRemoteDataSourceImpl.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/UserAuthService.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/UserService.kt
  app/src/main/java/com/ssafy/tott/data/model/request/BudgetRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/request/BudgetSaveRequest.kt
  app/src/main/java/com/ssafy/tott/data/model/response/BudgetResponse.kt
  app/src/main/java/com/ssafy/tott/data/model/response/ExtraMoneyResponse.kt
  app/src/main/java/com/ssafy/tott/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/di/NetworkModule.kt
  app/src/main/java/com/ssafy/tott/domain/model/ExtraMoney.kt
  app/src/main/java/com/ssafy/tott/domain/repository/UserRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/LoadExtraMoneyUseCase.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/SaveExtraMoneyUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/extramoney/ExtraMoneyActivity.kt
  app/src/main/java/com/ssafy/tott/ui/extramoney/ExtraMoneyViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/res/layout/activity_extra_money.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#57 전세 대출 상한 API 구현
  app/src/main/java/com/ssafy/tott/data/datasource/BuildingDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/BuildingRemoteDataSourceImpl.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserRemoteDataSource.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/UserRemoteRemoteDataSourceImpl.kt
  app/src/main/java/com/ssafy/tott/data/datasource/remote/service/UserAuthService.kt
  app/src/main/java/com/ssafy/tott/data/model/response/ComprehensiveBudgetResponse.kt
  app/src/main/java/com/ssafy/tott/data/repository/BuildingRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/di/DataModule.kt
  app/src/main/java/com/ssafy/tott/domain/model/ComprehensiveBudget.kt
  app/src/main/java/com/ssafy/tott/domain/repository/UserRepository.kt
  app/src/main/java/com/ssafy/tott/domain/usecase/GetComprehensiveMoneyUseCase.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeViewModel.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature

#59 필터 설정, 매물 상세 정보에 대출 상한 API 적용
  app/src/main/java/com/ssafy/tott/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/ssafy/tott/ui/buildingdetail/BuildingDetailActivity.kt
  app/src/main/java/com/ssafy/tott/ui/buildingdetail/BuildingDetailViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/home/HomeActivity.kt
  app/src/main/java/com/ssafy/tott/ui/houselist/BuildingDetailListAdapter.kt
  app/src/main/java/com/ssafy/tott/ui/searchfilter/SearchFilterFragment.kt
  app/src/main/java/com/ssafy/tott/ui/searchfilter/SearchFilterViewModel.kt
  app/src/main/java/com/ssafy/tott/ui/util/ImageLoader.kt
  app/src/main/res/drawable/house1.jpeg
  app/src/main/res/drawable/house2.jpg
  app/src/main/res/drawable/house3.jpeg
  app/src/main/res/drawable/house4.jpg
  app/src/main/res/layout/activity_building_detail.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_search_map.xml
  app/src/main/res/layout/fragment_search_filter.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feature
